workflows:
  ios_build:
    name: iOS build
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - flutter pub get
      - flutter build ipa --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
